apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
  labels:
    app: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: vladimirchuprazov/auth
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: JWT_SECRET
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-postgres-config
                  key: DATABASE_URL
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-postgres-config
                  key: POSTGRES_DB
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  JWT_SECRET: NDAgNzQgMGQgYzIgM2YgMzMgNTMgMGIgOWQgYTQgMTggMzEgODEgZjQgYmEgYjY=
